### ISSUE TITLE
Does the CUDA version of the library call have a demo  

### ISSUE THREAD

**Issue by taotaolin** [filecoin-project/rust-gpu-tools#37]
I successfully implemented a demo using Rustacuda. When calling rust-gpu-tools, I don't know how to use it. Do you have a CUDA version  

Thanks

**Comment by vmx** [comment]
A CUDA version is currently work in progress. It is not merged yet, but it is actively worked on.

**Comment by taotaolin** [comment]
> A CUDA version is currently work in progress. It is not merged yet, but it is actively worked on.

I'm using a CUDA branch and this branch doesn't work right now. I'm calling CUDA invalidContext when I'm using create_buffer.

**Comment by taotaolin** [comment]
Does the rust-gpu-tools CUDA branch work properly?  I'm trying to use this library

**Comment by vmx** [comment]
It's work in progress, I force-push to the branch. Currently it indeed doesn't work, but it should work again soon.

**Comment by taotaolin** [comment]
I know， Thank you

**Comment by vmx** [comment]
It took a long time, but finally there is a release with CUDA support out and there's also an example in the [examples directory](https://github.com/filecoin-project/rust-gpu-tools/tree/d3b36477c7d2017e2b7ea284fd91342a667835db/examples).

For a more elaborate, real world example, see the [bellperson](https://github.com/filecoin-project/bellperson) project. There the CUDA kernel is [compiled at build time](https://github.com/filecoin-project/bellperson/blob/6a24bf6d42105c3f9ad344d512c4637bb5211075/build.rs#L3-L81), those bytes are then used to [create the `Program`](https://github.com/filecoin-project/bellperson/blob/6a24bf6d42105c3f9ad344d512c4637bb5211075/src/gpu/program.rs#L64-L89).

**Comment by vmx** [comment]
I think this one is solved, hence closing it. If you've further questions, feel free to re-open or open a new issue.
