### ISSUE TITLE
Detection of RX 6800 XT Fails

### ISSUE THREAD

**Issue by chuck-r** [filecoin-project/rust-gpu-tools#45]
I know that this card isn't officially supported, but even with `BELLMAN_CUSTOM_GPU=gfx1030:4608` set, it fails to find my card. Odd that it works with a RX 3700, but not this card.

When running rust-fil-proofs' `benchy` app with `RUST_LOG=Trace` set, I get this output:

> 2021-07-14T21:45:58.249 INFO bellperson::groth16::prover > starting proof timer
> 2021-07-14T21:45:58.250 TRACE bellperson::groth16::prover > acquiring priority lock
> 2021-07-14T21:45:58.250 DEBUG bellperson::gpu::locks > Acquiring priority lock at "/tmp/bellman.priority.lock" ...
> 2021-07-14T21:45:58.250 DEBUG bellperson::gpu::locks > Priority lock acquired!
> 2021-07-14T21:45:58.250 INFO bellperson::gpu::locks > GPU is available for FFT!
> 2021-07-14T21:45:58.250 DEBUG bellperson::gpu::locks > Acquiring GPU lock at "/tmp/bellman.gpu.lock" ...
> 2021-07-14T21:45:58.250 DEBUG bellperson::gpu::locks > GPU lock acquired!
> 2021-07-14T21:45:58.653 DEBUG rust_gpu_tools::opencl::utils > loaded devices: {Amd: []}
> 2021-07-14T21:45:58.653 DEBUG bellperson::gpu::locks > GPU lock released!
> 2021-07-14T21:45:58.653 WARN bellperson::domain > Cannot instantiate GPU FFT kernel! Error: GPUError: No working GPUs found!
> 2021-07-14T21:45:58.658 INFO bellperson::gpu::locks > GPU is available for FFT!
> 2021-07-14T21:45:58.658 DEBUG bellperson::gpu::locks > Acquiring GPU lock at "/tmp/bellman.gpu.lock" ...
> 2021-07-14T21:45:58.658 DEBUG bellperson::gpu::locks > GPU lock acquired!
> 2021-07-14T21:45:58.658 DEBUG bellperson::gpu::locks > GPU lock released!
> 2021-07-14T21:45:58.658 WARN bellperson::domain > Cannot instantiate GPU FFT kernel! Error: GPUError: No working GPUs found!
> 2021-07-14T21:45:58.664 INFO bellperson::gpu::locks > GPU is available for FFT!
> 2021-07-14T21:45:58.664 DEBUG bellperson::gpu::locks > Acquiring GPU lock at "/tmp/bellman.gpu.lock" ...
> 2021-07-14T21:45:58.664 DEBUG bellperson::gpu::locks > GPU lock acquired!
> 2021-07-14T21:45:58.664 DEBUG bellperson::gpu::locks > GPU lock released!
> 2021-07-14T21:45:58.664 WARN bellperson::domain > Cannot instantiate GPU FFT kernel! Error: GPUError: No working GPUs found!
> 2021-07-14T21:45:58.668 INFO bellperson::gpu::locks > GPU is available for FFT!
> 2021-07-14T21:45:58.668 DEBUG bellperson::gpu::locks > Acquiring GPU lock at "/tmp/bellman.gpu.lock" ...
> 2021-07-14T21:45:58.668 DEBUG bellperson::gpu::locks > GPU lock acquired!
> 2021-07-14T21:45:58.668 DEBUG bellperson::gpu::locks > GPU lock released!
> 2021-07-14T21:45:58.668 WARN bellperson::domain > Cannot instantiate GPU FFT kernel! Error: GPUError: No working GPUs found!
> 2021-07-14T21:45:58.671 INFO bellperson::gpu::locks > GPU is available for FFT!
> 2021-07-14T21:45:58.671 DEBUG bellperson::gpu::locks > Acquiring GPU lock at "/tmp/bellman.gpu.lock" ...
> 2021-07-14T21:45:58.671 DEBUG bellperson::gpu::locks > GPU lock acquired!
> 2021-07-14T21:45:58.671 DEBUG bellperson::gpu::locks > GPU lock released!
> 2021-07-14T21:45:58.671 WARN bellperson::domain > Cannot instantiate GPU FFT kernel! Error: GPUError: No working GPUs found!
> 2021-07-14T21:45:58.676 INFO bellperson::gpu::locks > GPU is available for FFT!
> 2021-07-14T21:45:58.676 DEBUG bellperson::gpu::locks > Acquiring GPU lock at "/tmp/bellman.gpu.lock" ...
> 2021-07-14T21:45:58.676 DEBUG bellperson::gpu::locks > GPU lock acquired!
> 2021-07-14T21:45:58.676 DEBUG bellperson::gpu::locks > GPU lock released!
> 2021-07-14T21:45:58.676 WARN bellperson::domain > Cannot instantiate GPU FFT kernel! Error: GPUError: No working GPUs found!
> 2021-07-14T21:45:58.680 INFO bellperson::gpu::locks > GPU is available for FFT!
> 2021-07-14T21:45:58.680 DEBUG bellperson::gpu::locks > Acquiring GPU lock at "/tmp/bellman.gpu.lock" ...
> 2021-07-14T21:45:58.680 DEBUG bellperson::gpu::locks > GPU lock acquired!
> 2021-07-14T21:45:58.680 DEBUG bellperson::gpu::locks > GPU lock released!
> 2021-07-14T21:45:58.680 WARN bellperson::domain > Cannot instantiate GPU FFT kernel! Error: GPUError: No working GPUs found!
> 2021-07-14T21:45:58.693 INFO bellperson::gpu::locks > GPU is available for Multiexp!
> 2021-07-14T21:45:58.693 DEBUG bellperson::gpu::locks > Acquiring GPU lock at "/tmp/bellman.gpu.lock" ...
> 2021-07-14T21:45:58.693 DEBUG bellperson::gpu::locks > GPU lock acquired!
> 2021-07-14T21:45:58.693 DEBUG bellperson::gpu::locks > GPU lock released!
> 2021-07-14T21:45:58.693 WARN bellperson::multiexp > Cannot instantiate GPU Multiexp kernel! Error: GPUError: No working GPUs found!
> 2021-07-14T21:45:58.734 INFO bellperson::gpu::locks > GPU is available for Multiexp!
> 2021-07-14T21:45:58.734 DEBUG bellperson::gpu::locks > Acquiring GPU lock at "/tmp/bellman.gpu.lock" ...
> 2021-07-14T21:45:58.734 DEBUG bellperson::gpu::locks > GPU lock acquired!
> 2021-07-14T21:45:58.734 DEBUG bellperson::gpu::locks > GPU lock released!
> 2021-07-14T21:45:58.734 WARN bellperson::multiexp > Cannot instantiate GPU Multiexp kernel! Error: GPUError: No working GPUs found!
> 2021-07-14T21:45:58.762 INFO bellperson::gpu::locks > GPU is available for Multiexp!
> 2021-07-14T21:45:58.762 DEBUG bellperson::gpu::locks > Acquiring GPU lock at "/tmp/bellman.gpu.lock" ...
> 2021-07-14T21:45:58.762 DEBUG bellperson::gpu::locks > GPU lock acquired!
> 2021-07-14T21:45:58.762 DEBUG bellperson::gpu::locks > GPU lock released!
> 2021-07-14T21:45:58.762 WARN bellperson::multiexp > Cannot instantiate GPU Multiexp kernel! Error: GPUError: No working GPUs found!
> 2021-07-14T21:45:58.763 INFO bellperson::gpu::locks > GPU is available for Multiexp!
> 2021-07-14T21:45:58.763 DEBUG bellperson::gpu::locks > Acquiring GPU lock at "/tmp/bellman.gpu.lock" ...
> 2021-07-14T21:45:58.763 DEBUG bellperson::gpu::locks > GPU lock acquired!
> 2021-07-14T21:45:58.763 DEBUG bellperson::gpu::locks > GPU lock released!
> 2021-07-14T21:45:58.763 WARN bellperson::multiexp > Cannot instantiate GPU Multiexp kernel! Error: GPUError: No working GPUs found!
> 2021-07-14T21:45:58.785 INFO bellperson::gpu::locks > GPU is available for Multiexp!
> 2021-07-14T21:45:58.785 DEBUG bellperson::gpu::locks > Acquiring GPU lock at "/tmp/bellman.gpu.lock" ...
> 2021-07-14T21:45:58.785 DEBUG bellperson::gpu::locks > GPU lock acquired!
> 2021-07-14T21:45:58.785 DEBUG bellperson::gpu::locks > GPU lock released!
> 2021-07-14T21:45:58.785 WARN bellperson::multiexp > Cannot instantiate GPU Multiexp kernel! Error: GPUError: No working GPUs found!
> 2021-07-14T21:45:58.785 INFO bellperson::gpu::locks > GPU is available for Multiexp!
> 2021-07-14T21:45:58.785 DEBUG bellperson::gpu::locks > Acquiring GPU lock at "/tmp/bellman.gpu.lock" ...
> 2021-07-14T21:45:58.785 DEBUG bellperson::gpu::locks > GPU lock acquired!
> 2021-07-14T21:45:58.785 DEBUG bellperson::gpu::locks > GPU lock released!
> 2021-07-14T21:45:58.785 WARN bellperson::multiexp > Cannot instantiate GPU Multiexp kernel! Error: GPUError: No working GPUs found!
> 2021-07-14T21:45:58.810 INFO bellperson::gpu::locks > GPU is available for Multiexp!
> 2021-07-14T21:45:58.810 DEBUG bellperson::gpu::locks > Acquiring GPU lock at "/tmp/bellman.gpu.lock" ...
> 2021-07-14T21:45:58.810 DEBUG bellperson::gpu::locks > GPU lock acquired!
> 2021-07-14T21:45:58.810 DEBUG bellperson::gpu::locks > GPU lock released!
> 2021-07-14T21:45:58.810 WARN bellperson::multiexp > Cannot instantiate GPU Multiexp kernel! Error: GPUError: No working GPUs found!
> 2021-07-14T21:45:58.811 INFO bellperson::gpu::locks > GPU is available for Multiexp!
> 2021-07-14T21:45:58.811 DEBUG bellperson::gpu::locks > Acquiring GPU lock at "/tmp/bellman.gpu.lock" ...
> 2021-07-14T21:45:58.811 DEBUG bellperson::gpu::locks > GPU lock acquired!
> 2021-07-14T21:45:58.811 DEBUG bellperson::gpu::locks > GPU lock released!
> 2021-07-14T21:45:58.811 WARN bellperson::multiexp > Cannot instantiate GPU Multiexp kernel! Error: GPUError: No working GPUs found!
> 2021-07-14T21:45:58.870 TRACE bellperson::groth16::prover > dropping priority lock
> 2021-07-14T21:45:58.870 DEBUG bellperson::gpu::locks > Priority lock released!
> 2021-07-14T21:45:58.870 INFO bellperson::groth16::prover > prover time: 621.192123ms
> 2021-07-14T21:45:58.871 INFO storage_proofs_core::compound_proof > snark_proof:finish

What catches my attention is: `2021-07-14T21:45:58.653 DEBUG rust_gpu_tools::opencl::utils > loaded devices: {Amd: []}`. It seems it can find my OpenCL platform, but for some reason it just doesn't find my card.

clinfo:

> Number of platforms                               1
>   Platform Name                                   AMD Accelerated Parallel Processing
>   Platform Vendor                                 Advanced Micro Devices, Inc.
>   Platform Version                                OpenCL 2.0 AMD-APP (3261.0)
>   Platform Profile                                FULL_PROFILE
>   Platform Extensions                             cl_khr_icd cl_amd_event_callback 
>   Platform Extensions function suffix             AMD
> 
>   Platform Name                                   AMD Accelerated Parallel Processing
> Number of devices                                 1
>   Device Name                                     gfx1030
>   Device Vendor                                   Advanced Micro Devices, Inc.
>   Device Vendor ID                                0x1002
>   Device Version                                  OpenCL 2.0 
>   Driver Version                                  3261.0 (HSA1.1,LC)
>   Device OpenCL C Version                         OpenCL C 2.0 
>   Device Type                                     GPU
>   Device Board Name (AMD)                         Navi 21 [Radeon RX 6800/6800 XT / 6900 XT]
>   Device PCI-e ID (AMD)                           0x73bf
>   Device Topology (AMD)                           PCI-E, 0000:0a:00.0
>   Device Profile                                  FULL_PROFILE
>   Device Available                                Yes
>   Compiler Available                              Yes
>   Linker Available                                Yes
>   Max compute units                               36
>   SIMD per compute unit (AMD)                     4
>   SIMD width (AMD)                                32
>   SIMD instruction width (AMD)                    1
>   Max clock frequency                             2575MHz
>   Graphics IP (AMD)                               10.3
>   Device Partition                                (core)
>     Max number of sub-devices                     36
>     Supported partition types                     None
>     Supported affinity domains                    (n/a)
>   Max work item dimensions                        3
>   Max work item sizes                             1024x1024x1024
>   Max work group size                             256
>   Preferred work group size (AMD)                 256
>   Max work group size (AMD)                       1024
>   Preferred work group size multiple (kernel)     32
>   Wavefront width (AMD)                           32
>   Preferred / native vector sizes                 
>     char                                                 4 / 4       
>     short                                                2 / 2       
>     int                                                  1 / 1       
>     long                                                 1 / 1       
>     half                                                 1 / 1        (cl_khr_fp16)
>     float                                                1 / 1       
>     double                                               1 / 1        (cl_khr_fp64)
>   Half-precision Floating-point support           (cl_khr_fp16)
>     Denormals                                     No
>     Infinity and NANs                             No
>     Round to nearest                              No
>     Round to zero                                 No
>     Round to infinity                             No
>     IEEE754-2008 fused multiply-add               No
>     Support is emulated in software               No
>   Single-precision Floating-point support         (core)
>     Denormals                                     Yes
>     Infinity and NANs                             Yes
>     Round to nearest                              Yes
>     Round to zero                                 Yes
>     Round to infinity                             Yes
>     IEEE754-2008 fused multiply-add               Yes
>     Support is emulated in software               No
>     Correctly-rounded divide and sqrt operations  Yes
>   Double-precision Floating-point support         (cl_khr_fp64)
>     Denormals                                     Yes
>     Infinity and NANs                             Yes
>     Round to nearest                              Yes
>     Round to zero                                 Yes
>     Round to infinity                             Yes
>     IEEE754-2008 fused multiply-add               Yes
>     Support is emulated in software               No
>   Address bits                                    64, Little-Endian
>   Global memory size                              17163091968 (15.98GiB)
>   Global free memory (AMD)                        16760832 (15.98GiB) 16760832 (15.98GiB)
>   Global memory channels (AMD)                    8
>   Global memory banks per channel (AMD)           4
>   Global memory bank width (AMD)                  256 bytes
>   Error Correction support                        No
>   Max memory allocation                           14588628168 (13.59GiB)
>   Unified memory for Host and Device              No
>   Shared Virtual Memory (SVM) capabilities        (core)
>     Coarse-grained buffer sharing                 Yes
>     Fine-grained buffer sharing                   Yes
>     Fine-grained system sharing                   No
>     Atomics                                       No
>   Minimum alignment for any data type             128 bytes
>   Alignment of base address                       1024 bits (128 bytes)
>   Preferred alignment for atomics                 
>     SVM                                           0 bytes
>     Global                                        0 bytes
>     Local                                         0 bytes
>   Max size for global variable                    14588628168 (13.59GiB)
>   Preferred total size of global vars             17163091968 (15.98GiB)
>   Global Memory cache type                        Read/Write
>   Global Memory cache size                        16384 (16KiB)
>   Global Memory cache line size                   64 bytes
>   Image support                                   Yes
>     Max number of samplers per kernel             29631
>     Max size for 1D images from buffer            134217728 pixels
>     Max 1D or 2D image array size                 8192 images
>     Base address alignment for 2D image buffers   256 bytes
>     Pitch alignment for 2D image buffers          256 pixels
>     Max 2D image size                             16384x16384 pixels
>     Max 3D image size                             16384x16384x8192 pixels
>     Max number of read image args                 128
>     Max number of write image args                8
>     Max number of read/write image args           64
>   Max number of pipe args                         16
>   Max active pipe reservations                    16
>   Max pipe packet size                            1703726280 (1.587GiB)
>   Local memory type                               Local
>   Local memory size                               65536 (64KiB)
>   Local memory size per CU (AMD)                  65536 (64KiB)
>   Local memory banks (AMD)                        32
>   Max number of constant args                     8
>   Max constant buffer size                        14588628168 (13.59GiB)
>   Preferred constant buffer size (AMD)            16384 (16KiB)
>   Max size of kernel argument                     1024
>   Queue properties (on host)                      
>     Out-of-order execution                        No
>     Profiling                                     Yes
>   Queue properties (on device)                    
>     Out-of-order execution                        Yes
>     Profiling                                     Yes
>     Preferred size                                262144 (256KiB)
>     Max size                                      8388608 (8MiB)
>   Max queues on device                            1
>   Max events on device                            1024
>   Prefer user sync for interop                    Yes
>   Number of P2P devices (AMD)                     0
>   Profiling timer resolution                      1ns
>   Profiling timer offset since Epoch (AMD)        0ns (Wed Dec 31 18:00:00 1969)
>   Execution capabilities                          
>     Run OpenCL kernels                            Yes
>     Run native kernels                            No
>     Thread trace supported (AMD)                  No
>     Number of async queues (AMD)                  8
>     Max real-time compute queues (AMD)            8
>     Max real-time compute units (AMD)             36
>   printf() buffer size                            4194304 (4MiB)
>   Built-in kernels                                (n/a)
>   Device Extensions                               cl_khr_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_fp16 cl_khr_gl_sharing cl_amd_device_attribute_query cl_amd_media_ops cl_amd_media_ops2 cl_khr_image2d_from_buffer cl_khr_subgroups cl_khr_depth_images cl_amd_copy_buffer_p2p cl_amd_assembly_program 
> 
> NULL platform behavior
>   clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  AMD Accelerated Parallel Processing
>   clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   Success [AMD]
>   clCreateContext(NULL, ...) [default]            Success [AMD]
>   clCreateContextFromType(NULL, CL_DEVICE_TYPE_DEFAULT)  Success (1)
>     Platform Name                                 AMD Accelerated Parallel Processing
>     Device Name                                   gfx1030
>   clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
>   clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  Success (1)
>     Platform Name                                 AMD Accelerated Parallel Processing
>     Device Name                                   gfx1030
>   clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
>   clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
>   clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  Success (1)
>     Platform Name                                 AMD Accelerated Parallel Processing
>     Device Name                                   gfx1030
> 
> ICD loader properties
>   ICD loader Name                                 OpenCL ICD Loader
>   ICD loader Vendor                               OCL Icd free software
>   ICD loader Version                              2.3.0
>   ICD loader Profile                              OpenCL 3.0

lspci (relevant parts):

> 0a:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 21 [Radeon RX 6800/6800 XT / 6900 XT] [1002:73bf] (rev c1)

I have tried both the hybrid driver approach (open source OpenGL with AMDGPU-PRO OpenCL -- which is a working combination elsewhere) as well as the full proprietary AMDGPU-PRO driver (both with and without the `progl` command). I can confirm that OpenCL is working as GeekBench has no problem running OpenCL.

I can provide any other information needed and I don't mind running any custom test code.

**Comment by chuck-r** [comment]
Well, don't I feel dumb. I was using lotus v1.10.1, which uses rust-gpu-tools v0.3.0. All-the-while I'm referencing `master` code and can't figure out why it's not working. Turns out, the bug is fixed by changing AMD_DEVICE_VENDOR_STRING from 'AMD' to 'Advanced Micro Devices, Inc.' -- which has already been done in `master`. My apologies for any undue anxiety.

**Comment by vmx** [comment]
@chuck-r just to confirm. With current `master` (it didn't change since you opened your bug report), your graphics card is correctly detected?

**Comment by chuck-r** [comment]
It seems so. I am currently unable to complete the process though, due to a bad drive in my raid preventing benchmarks from succeeding. At least, that's what Slack believes. I get no kernel error messages, but `benchy` fails with a bus error panic as of right now.

**Comment by vmx** [comment]
@chuck-r it would be great of you could checkout current master of `rust-gpu-tools`, run `cargo test opencl::test::test_device_all -- --nocapture` and paste the output here. Ideally it will show your graphics card and upcoming releases of `rust-fil-proofs` should work fine.

**Comment by chuck-r** [comment]
Unfortunately, that's not the case. It doesn't detect the card properly. However, the following patch fixes the issue for my card (currently using 100% open source amdgpu drivers, but also worked on AMDGPU Pro drivers last I checked).

Output without patch:

```
$ RUST_BACKTRACE=1 cargo test opencl::test::test_device_all -- --nocapture
    Finished test [unoptimized + debuginfo] target(s) in 0.01s
     Running target/debug/deps/rust_gpu_tools-5e3481a66581adb7

running 1 test
thread 'opencl::test::test_device_all' panicked at 'No supported GPU found.', src/opencl/mod.rs:520:9
stack backtrace:
   0: std::panicking::begin_panic
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:519:12
   1: rust_gpu_tools::opencl::test::test_device_all
             at ./src/opencl/mod.rs:520:9
   2: rust_gpu_tools::opencl::test::test_device_all::{{closure}}
             at ./src/opencl/mod.rs:515:5
   3: core::ops::function::FnOnce::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/ops/function.rs:227:5
   4: core::ops::function::FnOnce::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test opencl::test::test_device_all ... FAILED

failures:

failures:
    opencl::test::test_device_all

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 4 filtered out; finished in 0.05s

error: test failed, to rerun pass '--lib'
```
Output with patch:
```
$ RUST_BACKTRACE=1 cargo test opencl::test::test_device_all -- --nocapture
   Compiling rust-gpu-tools v0.4.0 (/home/chuck/git/rust-gpu-tools)
    Finished test [unoptimized + debuginfo] target(s) in 0.32s
     Running /home/chuck/git/rust-gpu-tools/target/debug/deps/rust_gpu_tools-5e3481a66581adb7

running 1 test
device: Device { vendor: Amd, name: "gfx1030", memory: 17163091968, pci_id: PciId(2560), uuid: None, device: Device { id: 140487844535344 } }
test opencl::test::test_device_all ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 4 filtered out; finished in 0.05s
```

... and the  patch:
```
diff --git a/src/opencl/mod.rs b/src/opencl/mod.rs
index 393234c..973fc4d 100644
--- a/src/opencl/mod.rs
+++ b/src/opencl/mod.rs
@@ -19,7 +19,7 @@ use opencl3::memory::CL_MEM_READ_WRITE;
 use opencl3::program::ProgramInfo::CL_PROGRAM_BINARIES;
 use opencl3::types::CL_BLOCKING;
 
-const AMD_DEVICE_VENDOR_STRING: &str = "AMD";
+const AMD_DEVICE_VENDOR_STRING: &str = "Advanced Micro Devices, Inc.";
 const NVIDIA_DEVICE_VENDOR_STRING: &str = "NVIDIA Corporation";
```

**Comment by vmx** [comment]
Thanks @chuck-r for taking the time to help out. Could you please try this PR and see if it works for you: https://github.com/filecoin-project/rust-gpu-tools/pull/47?

**Comment by chuck-r** [comment]
```
RUST_BACKTRACE=1 cargo test opencl::test::test_device_all -- --nocapture
    Finished test [unoptimized + debuginfo] target(s) in 0.01s
     Running target/debug/deps/rust_gpu_tools-5e3481a66581adb7

running 1 test
device: Device { vendor: Amd, name: "gfx1030", memory: 17163091968, pci_id: PciId(2560), uuid: None, device: Device { id: 140403220257840 } }
test opencl::test::test_device_all ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 6 filtered out; finished in 0.04s
```

Checks out!

**Comment by vmx** [comment]
I'm closing this issue as it has been fixed and released.
