### ISSUE TITLE
About the meaning of "compute_units" in Device.

### ISSUE THREAD

**Issue by 20171759** [filecoin-project/rust-gpu-tools#74]
I want to know what the number of "compute_units" refers to in the NVIDIA device. In nvidia, computing units generally refer to the number of SPs. There are thousands in rtx 3060. However, when running the "trust gpu tools", I found the number of "compute_units" 28. So I am very curious about what "compute_units" refers to in the NVIDIA device.

**Comment by vmx** [comment]
I think I've answered the question, hence I close this issue. Feel free to re-open if it wasn't answered.
