### ISSUE TITLE
Suggestion to add some parameter for different GPU device

### ISSUE THREAD

**Issue by kikakkz** [filecoin-project/rust-gpu-tools#76]
**Motivation：**
when test with GPU for C2 task, we calculate chunk size and kernel size according to GPU cuda core count, with fix MAX_WINDOW_SIZE, MEMORY_PADDING. In my practice, for different GPU device, it may have better performance with different window_size, and different reserved memory. I'm not sure if we must keep some equation of different variables such as window_size, exp_bits, core_count. If not, it would be great to let user able to set different parameter for different GPU device.

**Practice:**
So, I implement some expand parameter for GPU info as following
![image](https://user-images.githubusercontent.com/13128505/224634082-e32464db-a05a-4705-b7c1-8c3f2a418937.png)
In such way, user can set different parameter for different GPU device to get better performance.
In my practice, for single 3080 device, we can improve performance for one C2 task from 14 minutes to 10.5 minutes.

**Discussion:**
I think I can help to finish this work if it's worth to do. But I still need more discussion of the meaning of parameter chunk_size_scale, best_chunk_size_scale which is a const in current implementation. And may be this implementation should be at upper layer, such as ec-gpu ?

**Comment by vmx** [comment]
In newer version of ec-gpu, the chunk size is not longer determined by the CUDA core count, but by the number of compute units/streaming multiprocessors (SM)  (the core count information is about to removed, see ).

Maintaining such a list in this library is out of scope as this library should not contain `ec-gpu` specific features. The place for something like this would be `ec-gpu`. Though even there I'd be hesitant. I'd rather trying to make the calculation better (based on the SM) or having it configurable, but not having any lists hard-coded in the source as it's a pain to maintain.

**Comment by kikakkz** [comment]
> In newer version of ec-gpu, the chunk size is not longer determined by the CUDA core count, but by the number of compute units/streaming multiprocessors (SM) (the core count information is about to removed, see #77).
> 
> Maintaining such a list in this library is out of scope as this library should not contain `ec-gpu` specific features. The place for something like this would be `ec-gpu`. Though even there I'd be hesitant. I'd rather trying to make the calculation better (based on the SM) or having it configurable, but not having any lists hard-coded in the source as it's a pain to maintain.

great to hear about that. i'll try new version ec-gpu.
