### ISSUE TITLE
Problems about 'NoBinaryForGpu'

### ISSUE THREAD

**Issue by Akariya777** [filecoin-project/rust-gpu-tools#79]
I want to run the example, but it failed with 
```
/rust-gpu-tools$ cargo run --example add
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/examples/add`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Cuda(NoBinaryForGpu)', examples/add.rs:10:76
```
I use Tesla K80 GPU and how can I solve it.

**Comment by vmx** [comment]
As you can see in the [source of add.rs](https://github.com/filecoin-project/rust-gpu-tools/blob/ff93a64e74bcd53e87c5aef90880b6aa29acb5a1/examples/add.rs#L6), the fatbin was compiled with `compute_52` as lowest version, but your Tesla K80 is compute_37.

You could try to compile it yourself with an older CUDA toolkit. Though you'd be on your own. This library supports only recent CUDA toolkits.

**Comment by Akariya777** [comment]
I changed the GPU to Tesla V100 and run the library correctly.
But the same question occurs when I use the library in my own codes.
Do I need to configure other CUDA settings?

**Comment by vmx** [comment]
You need to make sure you've compiled it for the correct architecture. I find https://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/ good to see which GPU works on which architecture.
