### ISSUE TITLE
No GPU found

### ISSUE THREAD

**Issue by LimesKey** [filecoin-project/rust-gpu-tools#86]
I want to create a program which obtains the user's GPU's (CUDA) Core Count or compute units using OpenCL. I'm running this crate on an Intel Iris Xe graphics card so it does not have CUDA capabilities but it has OpenCL capabilities. I'm a little new to Rust so please be easy on me.

I imported the crate into my cargo.toml as `rust-gpu-tools = {version = "0.7.2", features = ["opencl"]}`. Then I imported `use rust_gpu_tools::{opencl};`, when I try to run the program I get,
```rust
thread 'main' panicked at 'CUDA cannot find', C:\Users\Rick1\.cargo\registry\src\index.crates.io-6f17d22bba15001f\cuda-config-0.1.0\src\lib.rs:106:5
```
Is there any way to compile this crate without a CUDA device and use the OpenCL feature of it? Let me know if there is an easier way to do what I want to do.

**Comment by LimesKey** [comment]
I managed to fix this by downloading the [CUDA Toolkit ](https://developer.nvidia.com/cuda-downloads) but I am getting another error when trying to run,
```rust
error: process didn't exit successfully: `target\debug\password_llm.exe` (exit code: 0xc0000135, STATUS_DLL_NOT_FOUND)
```
This is my code,
```rust
#[allow(non_snake_case)]
#[allow(unused_imports)]

pub mod gpu {
    use rust_gpu_tools::{Device};
    pub fn obtainGPU() {
        let gpu_list = Device::all();
        let gpu = Device::name(gpu_list[0]);
        
        println!("Printing gpu info: \n");
        println!("{:?}", gpu);
    }
}
```

**Comment by LimesKey** [comment]
I managed to fix this too by downloading the nvcuda file from this [link](https://www.dll-files.com/nvcuda.dll.html), then I put the dll file in `C:\Windows\System32`. But before this, I had to first figure out what DLL file was causing it so I used dumpbin `dumpbin /dependents target\debug\password_llm.exe` then I searched through a few of the dependencies and found I didn't have the nvcuda.dll file on my system.

**Comment by LimesKey** [comment]
I seem to get no devices found whatsoever, not really sure what to do. I've tried many things but it can't find any devices.
```rust
pub mod gpu {
    use rust_gpu_tools::{opencl, Device, GPUError, Program, Vendor};

    pub fn obtainGPU() {
        let devices = Device::all();
        println!("{:?}", devices);
    }
}
```

**Comment by vmx** [comment]
Showing Intel devices was just added recently, in the past only AMD and NVidia devices where shown.

Can you try it again with adding:

```
rust-gpu-tools = { git = "https://github.com/filecoin-project/rust-gpu-tools", features = ["opencl"]}
```

and see if it then shows your device?

You could also try (for debugging purpose) to run the `add` example via `cargo run --example add`. No output means that no device was found.

**Comment by LimesKey** [comment]
That worked! Thanks @vmx, but I ended up just using opencl3 as it had all the features I wanted. Although it is a little harder to use, I already wrote all the code for it.
